os: linux
dist: xenial
language: python
python:
  - "3.8"
addons:
  chrome: stable

before_script:
  - chmod +x ./Pure_Beurre/manage.py
  - chmod +x ./Pure_Beurre/substitute/project_tester/chromedriver
  - chmod +x ./Pure_Beurre/substitute/project_tester/operadriver_linux64/operadriver
  - pip install -r requirements.txt
  - psql -c 'create database purebeurre;' -U postgres
branches:
  only:
    - stagging
services:
  - postgresql
script:
  - pwd
  - google-chrome --version
  - whereis google-chrome
  - ./Pure_Beurre/manage.py makemigrations
  - ./Pure_Beurre/manage.py migrate
  - ./Pure_Beurre/manage.py environs
  #- ./Pure_Beurre/manage.py tests


