language: python
python:
  - 3.8
before_script:
  - pip install -r requirements.txt
branches:
  only:
    - main
env : DJANGO_SETTINGS_MODULE="Pure_Beurre.settings.travis"
services:
  - postgresql
script:
  - ./manage.py tests