language: python
python:
  - "3.8"
before_script:
  - chmod +x ./Pure_Beurre/manage.py
  - pip install -r requirements.txt
branches:
  only:
    - main
services:
  - postgresql
script:
  - pwd
  - pytest ./Pure_Beurre/substitute/project_tester/tests.py
  - ./Pure_Beurre/manage.py tests
