language: python
python:
  - "3.8"
before_script:
  - chmod +x ./Pure_Beurre/manage.py
  - pip install -r requirements.txt
branches:
  only:
    - main
services:
  - postgresql
script:
  - pwd
  - cd Pure_Beurre/substitute/&&pytest project_tester/
  - ./Pure_Beurre/manage.py tests
