language: python
python:
  - "3.8"
before_script:
  - chmod +x ./Pure_Beurre/manage.py
  - pip install -r requirements.txt
  - psql -c 'create database purebeurre;' -U postgres
branches:
  only:
    - main
services:
  - postgresql
script:
  - pwd
  - ./Pure_Beurre/manage.py tests
  - exit
